# Generated by Django 3.2.25 on 2024-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('identification', models.CharField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('native_of', models.CharField(blank=True, max_length=1024, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('son_count', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('higher_education_in_date', models.DateTimeField(blank=True, null=True)),
                ('university_in_date', models.DateTimeField(blank=True, null=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('scale', models.FloatField(blank=True, null=True)),
                ('academic_index', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
